### PR TITLE
Implemented postprocess_ltrretriever

### PR DESCRIPTION
**Pull request by GallVp**
Here I have implemented POSTPROCESS_LTRRETRIEVER following a design pattern that may be implementable for other similar cases throughout the pipeline. Key details are:

- A single post processing script is lifted out of EDTA_raw.pl and placed into a perl script named `postprocess_ltrretriever.pl`. Changes in the script are kept minimal to facilitate upstream updates. 
- All the `util` scripts needed for postprocess_ltrretriever.pl are placed in `bin`.
- Conda environment file and docker container are included to support Conda/Docker/Singularity engines.
- Moved the ltrretriever sub workflow from `main.nf` to `fasta_ ltrretriever` as an independent sub workflow to keep `main.nf` minimal.
- Patched `nf-core/ltrretriever_ltrretriever` module with `nf-core modules patch ltrretriever/ltrretriever` to version track local changes.

Overall, I am not satisfied with lumping `mdust`, `tfr` and `TEsorter` in a single model as it is hard to optimise and test. But as we decided earlier, we should work towards a working version and then optimise. Next I'll be implementing this pattern for REPEATMODLER as I have a nf-core style module already implemented for REPEATMODLER.

Cheers
Usman R.

### CODE REVIEW

**Comment by GallVp** [comment]
HI @jguhlin 

I'll keep pushing new changes here. Starting this week I have a bit of time on my hand so I'll be working on EDTA NextFlow every Wednesday and Thursday.

**Comment by GallVp** [comment]
I have setup a components repo with CI for NextFlow modules/subworkflows. Please see an example PR here: https://github.com/GallVp/edta-components/pull/1

It tests using conda/docker/singularity. We can create reusable independently testable modules/subworkflows there and then install them here.

**Comment by jguhlin** [comment]
Awesome! I'm still catching up from travel this week, but will be back at
it next week

**Comment by GallVp** [comment]
Hi @jguhlin 

Can you kindly merge this PR?

**Comment by jguhlin** [comment]
Sorry about that!

**Pull request merged**
