### PR TITLE
nf-core style implementation

### PR DESCRIPTION
**Pull request by GallVp**
Hi @jguhlin 

I have added the ltrretriever workflow by using nf-core implementation style. There is lot going on in this PR and it might be easier to talk in person. Here, I'll summarise the key changes.

- We can switch back and forth between the original implementation (WORKFLOW_A) and the nf-core style implementation (WORKFLOW_B) by (un)commenting line 331 in `main.nf`
- Installed the modules from nf-core and PFR local repo with `nf-core -v modules install <tool/subtool>`
- Added execution profiles for local, PFR, docker, singularity and conda. To test with conda, please do:

```bash
./main.nf -profile local,conda -resume -c conf/test.config
```

- WORKFLOW_B also supports `-stub` and I have used to create a minimal continuous integration workflow.

Cheers

### CODE REVIEW

**Comment by jguhlin** [comment]
This looks great! I'm leaving town tomorrow, so I'm in low "work mode," but I'll try to get this merged in today.

The fffx sanitizer shortens the fasta IDs and is more efficient than bringing in a Python container (or any Python), so I think we should use that for workflow_b. But I'm going to leave it now; we could use that for restoring the IDs as well. It's statically compiled and can be compiled with musl, so conda should be plenty. 

Workflow_b needs to be adjusted to call the current subworkflow's process_output still for each module to get it in the format for 

We may have to test with the first chr of B73 (corn), because if there aren't enough TE's of the specific type then there is 0 output, which is either a failure or at least prevents the process_output step from occuring/being tested. But it does take a while; maybe we can do something with stubs? 

base.config is great, do you know if there's a way to set the process requirements dynamically? We could make some guesstimates on genome size. That's going to be one of the biggest problems. 

I think since workflow_b is the style we will ultimately end up using, we can use the existing local subworkflows there until they are integrated into nf-core modules?

**Comment by GallVp** [comment]
Thank you @jguhlin 

- Let's find a docker container such as ubuntu LTS which can run fffx. We have to support conda, docker and singularity. At PFR we don't use conda because our system is too fragile to handle conda build. It fails frequently. On AWS, conda is a good choice though as it is quite stable.
- I have run the current EDTA on chr1 of _A. chinensis_, it produces all the outputs. Happy to switch to any other small dataset though. I am using chr1 of _A. chinensis_ because I got it info nf-core datasets repo.
- In base.config, we can include `max_genome_size` param in addition to `max_cpus` etc to _dynamically_ allocate resources. This is however an experimental idea and not supported by nf-core template. Perhaps we can try this once we have made good progress on other fronts.
- Getting stuff into nf-core can be painstakingly slow sometimes. I think we should only put stuff there which can be used by other pipelines. Otherwise, we create local sub workflows and modules following the design patterns in [nf-core/rnaseq](https://github.com/nf-core/rnaseq/blob/master/subworkflows/local/align_star/main.nf)

**Comment by jguhlin** [comment]
Do you think moving the process outputs for each program to a process submodule makes the most sense? Then we could name them for the program they work with?

**Comment by GallVp** [comment]
Sorry I don't understand the question. Can you kindly give an example? I am also happy to have a call after 12 today.

**Comment by jguhlin** [comment]
Most of the programs used by EDTA have a processing step, as in:
https://github.com/jguhlin/EDTA/blob/51522e084a1310bc1f2c75da7ae1098741d458ad/subworkflows/local/ltr_retriever/main.nf#L33

https://github.com/jguhlin/EDTA/blob/51522e084a1310bc1f2c75da7ae1098741d458ad/subworkflows/local/annosine/main.nf#L24

https://github.com/jguhlin/EDTA/blob/51522e084a1310bc1f2c75da7ae1098741d458ad/subworkflows/local/repeatmodeler/main.nf#L20

I'm just wondering where to centralize it since I'm assuming they aren't part of the upstream modules?

**Comment by GallVp** [comment]
Yes, got it now. Sorry for being slow.

- There is a `util` directory which should be merged with bin. Each script in util(bin) should have a corresponding local module in `modules/local` directory with same name.
- For example, `cleanup_tandem.pl ` in util(bin) will have `cleanup_tandem.nf` in `modules/local. The process name will be CLEANUP_TANDEM. This way these scripts and modules will remain findable.

**Comment by jguhlin** [comment]
Maybe. I don't see much benefit in making every small script and awk command a separate process. It would make it much more difficult to bring upstream changes to the pipeline and require a ton of extra boilerplate code. Right now it's basically copy-and-paste to bring over changes.

**Comment by GallVp** [comment]
- Yes, that a good point. All the scripts in `bin` can be made executable and then called from the process as `perl script.pl`. That will cleanup the process `script` block.
- I think we should aim for creating independently testable modules.
- If multiple scripts are woking together to perform a specific step in the pipeline, perhaps they should be called one after the other from within the same process. For example, script1.pl and script2.pl should be merged into process SCRIPT1_SCRIPT2.
- If Ou has already created a pipeline step, let's say step1.pl which calls script1.pl, script2.pl, script3.pl, ... 8.pl; I think we should work with step1.pl rather than the individual scripts. Unless breaking the step down provides significant improvement in performance via parallelisation. Though, we should defer such optimisations till we have a working pipeline.

**Comment by jguhlin** [comment]
That sounds good to me! :)

**Comment by GallVp** [comment]
Thank you @jguhlin 

I am not sure which part should I handle next. Should I work on integrating REPEATMODELER into WORKFLOW_B?

**Comment by GallVp** [comment]
Are you using vs code for development? Should I setup a few pre-commit based linting checks?

**Comment by jguhlin** [comment]
Yes to vscode. Lints are good.

Yeah make workflow b into a and start porting the rest of the modules into
it?

**Pull request merged**
