### PR TITLE
Add main.nf into the new branch

### PR DESCRIPTION
**Pull request by jguhlin**

### CODE REVIEW

**Comment by jguhlin** [comment]
@GallVp Shortened main.nf, let me know if I should trim it a bit more.

**Comment by GallVp** [comment]
@jguhlin 

That's good. Let's get this running with CONDA.
 Can you please add the `fffx` to `bin`, a minimal `nextflow.config` and a test command as comment in the `main.nf` which runs this short workflow on your computer using CONDA. I'll try to modify it to work with docker/singularity.

**Comment by jguhlin** [comment]
@GallVp I can do a static compile and put that into bin, but unless I put it in bioconda (planning to do it eventually anyways). But right now there's nothing from conda it needs to run.

Will get the test command tomorrow.

**Comment by GallVp** [comment]
> @GallVp I can do a static compile and put that into bin, but unless I put it in bioconda (planning to do it eventually anyways). But right now there's nothing from conda it needs to run.
> 
> Will get the test command tomorrow.

Static compile for Linux + x86 will do. Unless you are on windows. Can you cross compile?

**Comment by jguhlin** [comment]
On linux, can cross compile to whichever platform and CPU is needed.

**Comment by GallVp** [comment]
> On linux, can cross compile to whichever platform and CPU is needed.

Bioconda is one option. Another option is that we compile it for Linux + x86 or Linux + amd64 and then use a conda environment which provides Rust dynamic libraries or maybe even that can be skipped with a static compile?
But for Linux and macOS with other machine architectures such as arm8, etc. we include a ubuntu docker container. Docker can emulate amd64. This approach is similar to this module: https://github.com/Plant-Food-Research-Open/assemblyqc/blob/690e56b3d349ee32754c9cc1cfc5474308f682ee/modules/local/assemblathon_stats.nf#L6
which executes a perl script from bin but inside a standard ubuntu container.

**Comment by GallVp** [comment]
Hi @jguhlin 

I have added the CI action. Other changes include.

1. A minimal `nextflow.config` to list available profiles.
2. A `cleanNXF` script which clean up the current directory after a Nextflow run
3. A `params.outdir` parameter which can be used as a suffix for all results.

**Review by GallVp — APPROVED** [review]
The next step is to move the sanitize process to the `modules` folder and start including EDTA steps one by one.

**Comment by jguhlin** [comment]
@GallVp Great. I'll merge this one and start on that step. 

I'll also get some CI testing going for https://github.com/jguhlin/fffx-tools

**Pull request merged**
